# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/atsupdatecandidatesrequestdto'
require_relative '../shared/candidateresult'

module StackOne
  module Operations

    class AtsUpdateCandidateRequest < StackOne::Utils::FieldAugmented
      extend T::Sig


      field :ats_update_candidates_request_dto, Shared::AtsUpdateCandidatesRequestDto, { 'request': { 'media_type': 'application/json' } }

      field :id, String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }
      # The account identifier
      field :x_account_id, String, { 'header': { 'field_name': 'x-account-id', 'style': 'simple', 'explode': false } }


      sig { params(ats_update_candidates_request_dto: Shared::AtsUpdateCandidatesRequestDto, id: String, x_account_id: String).void }
      def initialize(ats_update_candidates_request_dto: nil, id: nil, x_account_id: nil)
        @ats_update_candidates_request_dto = ats_update_candidates_request_dto
        @id = id
        @x_account_id = x_account_id
      end
    end


    class AtsUpdateCandidateResponse < StackOne::Utils::FieldAugmented
      extend T::Sig

      # HTTP response content type for this operation
      field :content_type, String
      # Raw HTTP response; suitable for custom response parsing
      field :raw_response, Faraday::Response
      # HTTP response status code for this operation
      field :status_code, Integer
      # The candidate was successfully updated.
      field :candidate_result, T.nilable(Shared::CandidateResult)


      sig { params(content_type: String, raw_response: Faraday::Response, status_code: Integer, candidate_result: T.nilable(Shared::CandidateResult)).void }
      def initialize(content_type: nil, raw_response: nil, status_code: nil, candidate_result: nil)
        @content_type = content_type
        @raw_response = raw_response
        @status_code = status_code
        @candidate_result = candidate_result
      end
    end
  end
end
