# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/proxyrequestbody'

module StackOne
  module Operations

    class StackoneProxyRequestRequest < ::StackOne::Utils::FieldAugmented
      extend T::Sig

      # The request body
      field :proxy_request_body, Shared::ProxyRequestBody, { 'request': { 'media_type': 'application/json' } }
      # The account identifier
      field :x_account_id, String, { 'header': { 'field_name': 'x-account-id', 'style': 'simple', 'explode': false } }


      sig { params(proxy_request_body: Shared::ProxyRequestBody, x_account_id: String).void }
      def initialize(proxy_request_body: nil, x_account_id: nil)
        @proxy_request_body = proxy_request_body
        @x_account_id = x_account_id
      end
    end


    class StackoneProxyRequestResponse < ::StackOne::Utils::FieldAugmented
      extend T::Sig

      # HTTP response content type for this operation
      field :content_type, String
      # Raw HTTP response; suitable for custom response parsing
      field :raw_response, Faraday::Response
      # HTTP response status code for this operation
      field :status_code, Integer


      sig { params(content_type: String, raw_response: Faraday::Response, status_code: Integer).void }
      def initialize(content_type: nil, raw_response: nil, status_code: nil)
        @content_type = content_type
        @raw_response = raw_response
        @status_code = status_code
      end
    end
  end
end
