# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Operations
  

    class AtsListApplicationsOffersResponse < ::StackOne::Utils::FieldAugmented
      extend T::Sig

      # HTTP response content type for this operation
      field :content_type, ::String
      # Raw HTTP response; suitable for custom response parsing
      field :raw_response, ::Faraday::Response
      # HTTP response status code for this operation
      field :status_code, ::Integer
      # The offers related to the application with the given identifier were retrieved.
      field :offers_paginated, T.nilable(::StackOne::Shared::OffersPaginated)


      sig { params(content_type: ::String, raw_response: ::Faraday::Response, status_code: ::Integer, offers_paginated: T.nilable(::StackOne::Shared::OffersPaginated)).void }
      def initialize(content_type: nil, raw_response: nil, status_code: nil, offers_paginated: nil)
        @content_type = content_type
        @raw_response = raw_response
        @status_code = status_code
        @offers_paginated = offers_paginated
      end
    end
  end
end
