# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Operations
  

    class MarketingGetCampaignResponse < ::StackOne::Utils::FieldAugmented
      extend T::Sig

      # HTTP response content type for this operation
      field :content_type, ::String
      # Raw HTTP response; suitable for custom response parsing
      field :raw_response, ::Faraday::Response
      # HTTP response status code for this operation
      field :status_code, ::Integer
      # The campaign with the given identifier was retrieved.
      field :campaign_result, T.nilable(::StackOne::Shared::CampaignResult)


      sig { params(content_type: ::String, raw_response: ::Faraday::Response, status_code: ::Integer, campaign_result: T.nilable(::StackOne::Shared::CampaignResult)).void }
      def initialize(content_type: nil, raw_response: nil, status_code: nil, campaign_result: nil)
        @content_type = content_type
        @raw_response = raw_response
        @status_code = status_code
        @campaign_result = campaign_result
      end
    end
  end
end
