# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Operations
  

    class StackoneListLinkedAccountsRequest < ::StackOne::Utils::FieldAugmented
      extend T::Sig

      # The origin owner identifier of the results to fetch
      field :origin_owner_id, T.nilable(::String), { 'query_param': { 'field_name': 'origin_owner_id', 'style': 'form', 'explode': true } }
      # The provider of the results to fetch
      field :provider, T.nilable(::String), { 'query_param': { 'field_name': 'provider', 'style': 'form', 'explode': true } }


      sig { params(origin_owner_id: T.nilable(::String), provider: T.nilable(::String)).void }
      def initialize(origin_owner_id: nil, provider: nil)
        @origin_owner_id = origin_owner_id
        @provider = provider
      end
    end
  end
end
