# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Operations
  

    class StackoneUpdateAccountRequest < ::StackOne::Utils::FieldAugmented
      extend T::Sig


      field :id, ::String, { 'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': false } }

      field :patch_account_dto, ::StackOne::Shared::PatchAccountDto, { 'request': { 'media_type': 'application/json' } }


      sig { params(id: ::String, patch_account_dto: ::StackOne::Shared::PatchAccountDto).void }
      def initialize(id: nil, patch_account_dto: nil)
        @id = id
        @patch_account_dto = patch_account_dto
      end
    end
  end
end
