# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module StackOne
  module Shared

    class PatchAccountDto < ::StackOne::Utils::FieldAugmented
      extend T::Sig



      
      def initialize; end
    end
  end
end
