# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module StackOne
  module Shared

    class SocialLink < StackOne::Utils::FieldAugmented
      extend T::Sig

      # Type of the social link
      field :type, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('type') } }
      # URL of the social link
      field :url, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('url') } }


      sig { params(type: String, url: String).void }
      def initialize(type: nil, url: nil)
        @type = type
        @url = url
      end
    end
  end
end
