# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  
    # AssessmentsPackagesValue - The type of the description.
    class AssessmentsPackagesValue < T::Enum
      enums do
        RESPONSIBILITIES = new('responsibilities')
        SKILLS = new('skills')
        BENEFITS = new('benefits')
      end
    end
  end
end
