# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  
    # AtsCreateNotesRequestDtoValue - The visibility of the notes.
    class AtsCreateNotesRequestDtoValue < T::Enum
      enums do
        PRIVATE = new('private')
        PUBLIC = new('public')
      end
    end
  end
end
