# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  

    class Attachments < ::StackOne::Utils::FieldAugmented
      extend T::Sig


      field :content_type, T.nilable(::StackOne::Shared::AssessmentsResultsContentType), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('content_type') } }
      # The URL of the attachment.
      field :url, T.nilable(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('url') } }


      sig { params(content_type: T.nilable(::StackOne::Shared::AssessmentsResultsContentType), url: T.nilable(::String)).void }
      def initialize(content_type: nil, url: nil)
        @content_type = content_type
        @url = url
      end
    end
  end
end
