# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  
    # CampaignSchemasValue - The Status of the campaign.
    class CampaignSchemasValue < T::Enum
      enums do
        DRAFT = new('draft')
        ARCHIVED = new('archived')
        LIVE = new('live')
      end
    end

  end
end
