# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  
    # Confidential - Confidential status of the job
    class Confidential < T::Enum
      enums do
        TRUE = new('true')
        FALSE = new('false')
      end
    end
  end
end
