# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  

    class Content < ::StackOne::Utils::FieldAugmented
      extend T::Sig

      # The file format of the file
      field :file_format, T.nilable(::StackOne::Shared::FileFormatEnum), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('file_format') } }
      # URL where the file content is located
      field :url, T.nilable(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('url') } }


      sig { params(file_format: T.nilable(::StackOne::Shared::FileFormatEnum), url: T.nilable(::String)).void }
      def initialize(file_format: nil, url: nil)
        @file_format = file_format
        @url = url
      end
    end
  end
end
