# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  
    # ContentBlockValue - The Status of the content blocks.
    class ContentBlockValue < T::Enum
      enums do
        TEXT = new('text')
      end
    end

  end
end
