# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  
    # The unified message type.
    class EmailMessagesValue < ::StackOne::Utils::FieldAugmented
      extend T::Sig



      
      def initialize; end
    end
  end
end
