# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  
    # EmployeeSchemasNationalIdentityNumberValue - The type of the national identity number
    class EmployeeSchemasNationalIdentityNumberValue < T::Enum
      enums do
        SSN = new('ssn')
        NIN = new('nin')
        SIN = new('sin')
        OTHER = new('other')
        UNKNOWN = new('unknown')
      end
    end
  end
end
