# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  

    class EmployeeCustomFieldsValue < T::Enum
      enums do
        DATE = new('date')
        FLOAT = new('float')
        INTEGER = new('integer')
        LIST = new('list')
        TEXT = new('text')
        UNMAPPED_VALUE = new('unmapped_value')
      end
    end

  end
end
