# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  

    class EmployeeSchemasMaritalStatusValue < T::Enum
      enums do
        SINGLE = new('single')
        MARRIED = new('married')
        COMMON_LAW = new('common_law')
        DIVORCED = new('divorced')
        WIDOWED = new('widowed')
        DOMESTIC_PARTNERSHIP = new('domestic_partnership')
        SEPARATED = new('separated')
        OTHER = new('other')
        NOT_DISCLOSED = new('not_disclosed')
        UNMAPPED_VALUE = new('unmapped_value')
      end
    end

  end
end
