# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  

    class HRISLocationSchemasValue < T::Enum
      enums do
        HOME = new('home')
        WORK = new('work')
        UNMAPPED_VALUE = new('unmapped_value')
      end
    end

  end
end
