# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  
    # HRISBenefitValue - The type of the benefit
    class HRISBenefitValue < T::Enum
      enums do
        OTHER = new('other')
      end
    end

  end
end
