# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  

    class HrisCreateEmployeeRequestDtoSchemasEthnicityValue < T::Enum
      enums do
        WHITE = new('white')
        BLACK_OR_AFRICAN_AMERICAN = new('black_or_african_american')
        ASIAN = new('asian')
        HISPANIC_OR_LATINO = new('hispanic_or_latino')
        AMERICAN_INDIAN_OR_ALASKA_NATIVE = new('american_indian_or_alaska_native')
        NATIVE_HAWAIIAN_OR_PACIFIC_ISLANDER = new('native_hawaiian_or_pacific_islander')
        TWO_OR_MORE_RACES = new('two_or_more_races')
        NOT_DISCLOSED = new('not_disclosed')
        OTHER = new('other')
        UNMAPPED_VALUE = new('unmapped_value')
      end
    end
  end
end
