# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  

    class HrisDocumentsUploadRequestDto < ::StackOne::Utils::FieldAugmented
      extend T::Sig

      # The category to be associated with the file to be uploaded. Id will take precedence over name.
      field :category, T.nilable(::StackOne::Shared::HrisDocumentsUploadRequestDtoCategory), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('category') } }
      # The categoryId of the documents
      field :category_id, T.nilable(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('category_id') } }
      # The confidentiality level of the file to be uploaded
      field :confidential, T.nilable(::StackOne::Shared::Confidential), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('confidential') } }
      # The base64 encoded content of the file to upload
      field :content, T.nilable(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('content') } }
      # The file format of the file
      field :file_format, T.nilable(::StackOne::Shared::HrisDocumentsUploadRequestDtoFileFormat), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('file_format') } }
      # The filename of the file to upload
      field :name, T.nilable(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('name') } }
      # The path for the file to be uploaded to
      field :path, T.nilable(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('path') } }


      sig { params(category: T.nilable(::StackOne::Shared::HrisDocumentsUploadRequestDtoCategory), category_id: T.nilable(::String), confidential: T.nilable(::StackOne::Shared::Confidential), content: T.nilable(::String), file_format: T.nilable(::StackOne::Shared::HrisDocumentsUploadRequestDtoFileFormat), name: T.nilable(::String), path: T.nilable(::String)).void }
      def initialize(category: nil, category_id: nil, confidential: nil, content: nil, file_format: nil, name: nil, path: nil)
        @category = category
        @category_id = category_id
        @confidential = confidential
        @content = content
        @file_format = file_format
        @name = name
        @path = path
      end
    end
  end
end
