# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  
    # JobValue - The status of the job.
    class JobValue < T::Enum
      enums do
        PUBLISHED = new('published')
        DRAFT = new('draft')
        PENDING = new('pending')
        INTERNAL = new('internal')
        ARCHIVED = new('archived')
        CLOSED = new('closed')
        OPEN = new('open')
        DELETED = new('deleted')
        ON_HOLD = new('on_hold')
        UNMAPPED_VALUE = new('unmapped_value')
      end
    end
  end
end
