# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  

    class JobPostingQuestionnaire < ::StackOne::Utils::FieldAugmented
      extend T::Sig

      # Unique identifier
      field :id, T.nilable(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('id') } }

      field :internal, T.nilable(T::Boolean), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('internal') } }

      field :name, T.nilable(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('name') } }

      field :questions, T.nilable(T::Array[::StackOne::Shared::Question]), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('questions') } }
      # Provider's unique identifier
      field :remote_id, T.nilable(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('remote_id') } }


      sig { params(id: T.nilable(::String), internal: T.nilable(T::Boolean), name: T.nilable(::String), questions: T.nilable(T::Array[::StackOne::Shared::Question]), remote_id: T.nilable(::String)).void }
      def initialize(id: nil, internal: nil, name: nil, questions: nil, remote_id: nil)
        @id = id
        @internal = internal
        @name = name
        @questions = questions
        @remote_id = remote_id
      end
    end
  end
end
