# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  

    class LinkedAccountStatus < T::Enum
      enums do
        ACTIVE = new('Active')
        INACTIVE = new('Inactive')
        ERROR = new('Error')
      end
    end

  end
end
