# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  

    class LinkedAccountStatus < T::Enum
      enums do
        ACTIVE = new('active')
        INACTIVE = new('inactive')
        ERROR = new('error')
      end
    end
  end
end
