# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  
    # NoteValue - The visibility of the notes.
    class NoteValue < T::Enum
      enums do
        PRIVATE = new('private')
        PUBLIC = new('public')
      end
    end

  end
end
