# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  
    # UnifiedUploadRequestDtoValue - Whether the file is confidential or not
    class UnifiedUploadRequestDtoValue < T::Enum
      enums do
        TRUE = new('true')
        FALSE = new('false')
      end
    end

  end
end
