# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module StackOne
  module Shared
  
    # The category object for associating uploaded files. If both an ID and a name are provided, the ID takes precedence.
    class UnifiedUploadRequestDtoCategory < ::StackOne::Utils::FieldAugmented
      extend T::Sig

      # The provider specific category for associating uploaded files, if provided, the value will be ignored.
      field :source_value, T.nilable(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('source_value') } }
      # The category name for associating uploaded files.
      field :value, T.nilable(::String), { 'format_json': { 'letter_case': ::StackOne::Utils.field_name('value') } }


      sig { params(source_value: T.nilable(::String), value: T.nilable(::String)).void }
      def initialize(source_value: nil, value: nil)
        @source_value = source_value
        @value = value
      end
    end
  end
end
